### ISSUE TITLE
配置了，请求地址在浏览器能获取到数据，通过API会提示错误

### ISSUE THREAD

**Issue by fenzaiway** [shady2k/siyuan-inbox-telegram-plugin#1]
{"code":-1,"msg":"forward request failed: Post \"https://api.telegram.org/xxxxxxxxx_XX-dI3U3uhih-ips/getUpdates\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)","data":null}%

**Comment by shady2k** [comment]
Can you describe your problem with more details?

**Comment by fenzaiway** [comment]
来信已经收到，谢谢！--by Crazy Chester

**Comment by fenzaiway** [comment]
我已根据文档配置了token、日记本和账号，但是无法通过轮询请求获取到我TG账号bot的内容。然而，我可以直接在浏览器地址栏输入连接来获取数据。

**Comment by shady2k** [comment]
This error can occur if you are using a proxy on your system. If you are using a proxy, make sure to configure it in the Siyan app (Settings > About > Network Proxy). If you have a direct connection, ensure that the Siyan app is set to use a Direct connection. All network connections are routed through the Siyan app.
